### ISSUE TITLE
Timing issue

### ISSUE THREAD

**Issue by micooke** [micooke/WWVB#2]
I measured the output using an arduino nano, and it consistently transmits the full 60s frame in 60.5s.

Ill need to investigate this, but i believe i was using minimum_no_interrupt.ino which is a concern.

**Comment by micooke** [comment]
Fixed - i was using the interrupt counts (WWVB_LOW etc) from the wrong counter setup, they were literally switched. 

The comment was correct, the code was switched - this is how i picked it up.

**Comment by mr-sneezy** [comment]
Cool find.
I'm still away killing fish.
Will try it again when I get home.

Martin
