### ISSUE TITLE
No issue. First successful time set for me on a WWVB clock !

### ISSUE THREAD

**Issue by mr-sneezy** [micooke/WWVB#3]
**Hey, had success.** 
I just had a first success with minimum.ino in setting the time, date and year on a desk clock, then repeated again to make sure, with full success. 
Will test with a CASIO watch now...

**Comment by mr-sneezy** [comment]
<a data-flickr-embed="true"  href="https://www.flickr.com/photos/mr_sneezy/24390427272/in/dateposted-public/" title="test_board1"><img src="https://farm2.staticflickr.com/1636/24390427272_e06c1984f8_b.jpg" width="1024" height="769" alt="test_board1"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

**Comment by micooke** [comment]
Awesome news! Let me know how you go with the casio. 

Now all i need to do is calibrate the other setups im supporting.

Ill calibrate the 16MHz Atmega32u4 first, then check the Attiny85, then the 8MHz variants.

After that its time to revisit the gps demo and get the full system working.

**Comment by mr-sneezy** [comment]
Hi mate. Yes the Nano-with-GPS version doesn't work, tested it yesterday and again tonight.
Also tested simpleGPS again to be sure the GPS was up, I see that the parsed day of the month is out by 11...

RAW: 210116 @ 94933
10/1/17 (2017) @ 19:19:33.0
Travelling : 0.00 Knots @ {3453.78, -13840.00} {Lat, Lon}

$GPRMC,094934.00,A,3448.12345,S,13840.12345,E,0.041,,210116,,,A*

RAW: 210116 @ 94934
10/1/17 (2016) @ 19:19:34.0
Travelling : 0.00 Knots @ {3448.00, -13840.00} {Lat, Lon}

$GPRMC,094934.00,3448.12345,S,13840.12345,E,1,08,1.19,183.9,M,-3.1,M,,*

**Comment by mr-sneezy** [comment]
.
