### ISSUE TITLE
Hours not correct on minimum.ino

### ISSUE THREAD

**Issue by mr-sneezy** [micooke/WWVB#4]
Now the the excitement of a valid reading has settled I note that the hour value decoded by the clock is out by -6 hours. After a valid decode 10:30PM compile time, the clock reads 4:30PM (or really a bit later due to the few minutes the decode takes to happen). I'll try a recompile and try again to verify.
I set the time zone on the clock to CST, so there wouldn't be an offset...
Minutes, seconds, and date/year is OK.

**Comment by mr-sneezy** [comment]
Recompiled, yep still -6 hours on compile time (plus decoding time elapsed) displayed.

**Comment by micooke** [comment]
I've added a setTimezome for both AttinyGPS and wwvb so need to make sure that one of these is set to the correct time zone. The default 0,0 is UTC.
