### ISSUE TITLE
Too many big words Charlie 

### ISSUE THREAD

**Issue by micooke** [micooke/WWVB#5]
Minimum.ino is working but Nano_with_gps.ino and nano_with_gps2.ino are all over the place with pulse widths and are unable to be calibrated.

The issue is the gps parsing overhead that was added. I need to look into this, it may mean a two chip solution is required?

**Comment by mr-sneezy** [comment]
Feedback:
Tried the late Nano_with_GPS2.ino, also pulled down the AtTinyGPS stuff so it compiled.

Got this from the serial terminal over a minute or so
Waiting on first GPS sync error : NMEA string $GPTXT is not supported
error : NMEA string $GPTXT is not supported
.......error : NMEA string $bb’ is not supported
...error : NMEA string $lbb’ is not supported
.............................error : NMEA string $ŒŽrl is not supported
........error : NMEA string $bpœ is not supported
.error : NMEA string $�bŒbl is not supported
....error : NMEA string $ŒŽ`rl is not supported
..............error : NMEA string $lbnŽŒ is not supported
..................error : NMEA string $ŒŽbbb is not supported
.........................error : NMEA string $ŒŽ`rl is not supported
..error : NMEA string $b‚p is not supported
.....error : NMEA string $ì�’� is not supported
.....error : NMEA string $rrƒbì is not supported
.................error : NMEA string $ì�Œ is not supported
.......error : NMEA string $rr‚bì is not supported
...............

**Comment by micooke** [comment]
First things first - im changing this back to 9600 BAUD as some GPS units dont support 14400 BAUD.

As discussed - that issue is because some ublox GPS units dont accept PMTK command strings :-1: .
I do have a thought on that though - do a raw capture of the strings sent from u-connect when from you:
1. send RMC & GGA only
2. 1Hz update rate (or slower)

I think ive sorted out my issue - the interrupt was taking too long because of the processing overhead, so i have changed it a very small amount so that i dont need to do cli() before it (then sei() after).

**Comment by micooke** [comment]
Because of this bugfix :-1: the calibration i completed using minimum.ino is incorrect now

**Comment by mr-sneezy** [comment]
More feedback.
This is from Nano_with_GPS2. Looks more promising.

Waiting on first GPS sync .................. GPS synced!

##### GPS SYNCED

IsValid    : 1
Quality    : 1
Satellites : 9
Date/Time  : 05:53 on 14/02/2016
WWVB transmit started

**Comment by mr-sneezy** [comment]
[WWVB & Clocks output_250 kHz, 2 M Samples [7].zip](https://github.com/micooke/WWVB/files/129542/WWVB.Clocks.output_250.kHz.2.M.Samples.7.zip)

**Comment by mr-sneezy** [comment]
Added a Saleae capture of both the Nano's WWVB pin and a voltage boosted inverted (via a BC549 tranny) signal from the test clocks RX pin.

At this point in time I have not had a successful time sync on the clock with Nano_with_GPS2 (but did with minimum.ino. I guess there is still a timing issue on the WWVB.

**Comment by micooke** [comment]
I think i can safely close this with the latest update :smile:
