### ISSUE TITLE
Thanks, this works perfectly for me

### ISSUE THREAD

**Issue by pepsiplease69** [micooke/WWVB#8]
Not reporting an issue, but just sharing my experience.

I'm using an Arduino Micro and an Adafruit Ultimate GPS breakout.

I used one wire to connect GPS Tx ==> Arduino Micro Rx (pin 10)

I had to read up on what the sketch does and figure out the constructor for SoftwareSerial to see what pins were being used.

I didn't bother with connecting up the other direction (micro Tx => GPS Rx) since there are no commands going the other way.

I had a bit of difficulty with getting it working initially because I used a solid core 22AWG hookup wire as my antenna directly connected to pin 9, but I discovered it wasn't working, so then I did exactly as the diagram showed

pin 9 -> antenna
pin 9 -> R (110 ohm) -> LED -> GND
pin 9 -> C (1uF) -> GND

I think the capacitor might be helping convert the square wave coming out of pin 9 into a sine wave which is what my clock is looking for maybe?

The LED is properly blinking in it's (morse-code-ish) pattern.

I wanted to ask whether you have any recommendation on the antenna. Right now I'm using about a foot long 22AWG solid core hookup wire, I've coiled it up around a pencil but I need to have the clock right next to it in order for it to sync.

The way I know it all works is if I slightly modify the sketch to send day+1 over WWVB, I see my clock showing tomorrow's date instead of today after it's done synching. Thus proving that it's synching with my arduino instead of Colorado.

Thanks immensely for putting out this project.

**Comment by micooke** [comment]
Great news! So i can add it to my very small 'IT WORKS!'  list, what clock are you using?

Funnily enough, i dont actually have a wwvb clock - this all started as a 'quick' project to help out a mate (@mr-sneezy) 

Sneezy is using a loop antenna in this video  [(@mr-sneezy youtube vid)](https://www.youtube.com/watch?v=lA-yf535rdY). He 3D printed a bracket for the antenna - ill have to get him to add it to this project. Loop antennas are very broad band and easy to get working. I would use one instead of an end fire antenna like you describe. we have gotten it working using 5 or so loops about 10cm diameter. You don't need that circuit with a loop antenna, just inline a led (or 10k resistor). I.e. WWVB out => loop => +led- => ground. The led or resistor acts as a current limiter.

**Comment by pepsiplease69** [comment]
Hello Mark,
The clock I'm using is a really old one. It's notorious for not picking up Colorado.

Equity by La Crosse SkyScan 31269 LCD Atomic Alarm Clock
https://www.amazon.com/dp/B0001MHL1S/ref=wl_it_dp_o_pC_nS_ttl?_encoding=UTF8&colid=1X3TWXSCTQ0DI&coliid=I25OATSH4W0S4Q

I have a second clock I'm also going to test with to see if that one works.
La Crosse Technology WS-8418U-IT Atomic Digital Wall Clock with Moon Phase
https://www.amazon.com/gp/product/B0016MYATS/ref=oh_aui_search_detailpage?ie=UTF8&psc=1

This second one picks up the signal from Colorado just fine, but it was in the other room and the signal from the arduino was not strong enough to set this clock.

I will work on your suggestions about the antenna and see if it improves my signal.

There were a few lines in the code related to Calibration, should I do anything with that? or is that for special cases?

Thanks.

**Comment by micooke** [comment]
Thanks for the info!
The calibration data is there for the 60kHz carrier. In short, if your clock is syncing you don't need to modify it. I found the the register values needed to generate the 60kHz depends on the processing load and chip type. 

Another thought with the antenna, an rfid antenna at 125kHz should work.
@mr-sneezy design : http://www.thingiverse.com/thing:1358090
His design works out to a couple meters, so not a huge range but better than cm's, but i could probably design an amplifier circuit if you want greater range. It should only require an op amp, some diodes and capacitors. If you have a negative supply it simplifies the circuit i have in mind.

**Comment by micooke** [comment]
Alrighty - im closing this down 👍
